repos:
  - repo: local
    # instead of ln -s because pub.dev doesn't allow symlinks
    hooks:
      - id: sync-files
        name: Sync files to subpackage
        entry: bash scripts/sync_files.sh
        language: system
        types: [text]
