global_options:
  freezed:
    runs_before:
      - retrofit_generator
  json_serializable:
    runs_before:
      - retrofit_generator

targets:
  $default:
    builders:
      json_serializable:
        options:
          create_factory: true
          create_to_json: true
          explicit_to_json: true
          field_rename: snake
          include_if_null: false

      freezed:
        options:
          format: true
          copy_with: false
          map: false
          when:
            when: true
            maybe_when: true
            when_or_null: false
