name: swagger_to_dart
description: Convert Swagger to Dart using freezed and retrofit support only 3.1.0 openApi
version: 0.3.0
homepage: https://github.com/masreplay/swagger_to_dart
issue_tracker: https://github.com/masreplay/swagger_to_dart/issues
funding: [https://github.com/sponsors/masreplay]
topics: [swagger, openapi, generator, freezed, retrofit]

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.18.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path: ^1.9.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  lints: ^5.1.1
  test: ^1.24.0
