name: swagger_to_dart
description: Convert Swagger to Dart using freezed and retrofit
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  change_case: ^2.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lints: ^4.0.0
  test: ^1.24.0
