swagger_to_dart:
  # From FastAPI project running locally for example
  # url: http://127.0.0.1:8000/openapi.json

  # Where to save the openapi.json file
  input_directory: schema/swagger.json
  global_imports: 
  file_imports: 
  custom_api_response: 
    adapter_class_name: CustomApiResponseAdapter
    return_type_class_name: Result
    adapter_import_path: package:example/custom_api_response.dart
    return_type_import_path: package:example/custom_api_response.dart
  skipped_parameters:
    - "Accept-Language"
    - "X-Language"
    - "X-Platform"
