swagger_to_dart:
  # From FastAPI project running locally for example
  # url: http://127.0.0.1:8000/openapi.json

  # Where to save the openapi.json file
  input_directory: schema/swagger.json
  globalImports: 
  fileImports: 

  skipped_parameters:
    - "Accept-Language"
    - "X-Language"
    - "X-Platform"
