name: Publish swagger_to_dart to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Remove symlinks and copy actual files
        run: |
          rm -f packages/swagger_to_dart/README.md
          rm -f packages/swagger_to_dart/LICENSE
          rm -f packages/swagger_to_dart/CHANGELOG.md
          cp README.md packages/swagger_to_dart/README.md
          cp LICENSE packages/swagger_to_dart/LICENSE
          cp CHANGELOG.md packages/swagger_to_dart/CHANGELOG.md

      - name: Publish to pub.dev
        working-directory: packages/swagger_to_dart
        run: dart pub publish --force
