name: Publish swagger_to_dart to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  prepare-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Copy root files to package
        run: |
          cp README.md packages/swagger_to_dart/README.md
          cp LICENSE packages/swagger_to_dart/LICENSE
          cp CHANGELOG.md packages/swagger_to_dart/CHANGELOG.md

      - name: Publish to pub.dev
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
        with:
          working-directory: packages/swagger_to_dart
