name: Publish swagger_to_dart to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-output.outputs.dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Set working directory
        id: set-output
        run: echo "dir=packages/swagger_to_dart" >> "$GITHUB_OUTPUT"

      - name: Remove symlinks and copy actual files
        run: |
          rm -f packages/swagger_to_dart/README.md
          rm -f packages/swagger_to_dart/LICENSE
          rm -f packages/swagger_to_dart/CHANGELOG.md
          cp README.md packages/swagger_to_dart/README.md
          cp LICENSE packages/swagger_to_dart/LICENSE
          cp CHANGELOG.md packages/swagger_to_dart/CHANGELOG.md

  publish:
    needs: prepare
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/swagger_to_dart
